### PR TITLE
update some screenshots

### PR DESCRIPTION
**Pull request by rating89us**

### CODE REVIEW

**Review by erciccione — CHANGES_REQUESTED** [review]
All new screenshots are missing the bullet points.

**Comment by rating89us** [comment]
I'm not sure if they are really necessary.
It takes a lot of time to add these bullets, which could make hard updating screenshots and translated screenshots. 
Also, we have a single subsection for each Monero GUI page, and all explaining text items are numbered in order of appearance. 
These types of bullets are necessary when we want to explain different parts of the UI (for instance Menu + toolbar + page), not parts that are displayed in (logical) sequence in a single page.

**Comment by erciccione** [comment]
I'm fine with removing them if we want to go that way. Makes sense and is always a pain in the ass to make the screenshot and then add the bullet points. But if we go that way, we should also remove all the numbered lists first.

**Comment by rating89us** [comment]
Please merge these images and the other PRs first, and then I remove in another PR the numbered lists of screenshots without bullets.

But I think we should still use them only when they are useful: 

Here, not everyone may notice that English (US) is clickable:
image

Here (and other screenshots), when the UI elements are not one above the other:
image

image

**Comment by erciccione** [comment]
> But I think we should still use them only when they are useful

I agree. I'm merging this.

> then I remove in another PR the numbered lists of screenshots without bullets.

Looking forward to this. Thanks :)

**Review by erciccione — APPROVED** [review]

**Pull request merged**
