### PR TITLE
[74] Add language translation option for LaTex

### PR DESCRIPTION
**Pull request by Rho-n**
Update sub Makefiles to set lang option for LaTex engine when converting to pdf.

### CODE REVIEW

**Comment by erciccione** [comment]
Please rebase

**Comment by Rho-n** [comment]
I used the github edit-conflicts page to fix the issues. Not sure if this is sufficient. I have never used rebase, and am still trying to figure it out.

**Comment by Rho-n** [comment]
I mostly use git from the command line. It will be greatly appreciate, if you send me the commands, in  particular related to github work flow, and some good resources. Thanks!

**Comment by erciccione** [comment]
**To rebase a pull request when you have conflicts:**

`git pull upstream master --rebase` The rebase flag is needed to put your changes on top of the pulled upstream branch. Doing that git will tell you there are conflicts and where. Fix them, add the fixed file using `git add [file]` then go on with the rebase using `git rebase --continue`. When done with that, you can force push the changes to your remote branch.

**If you need to squash commits**

Just follow the instructions here: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request#squash-your-changes

**Also:**

+ This article give you some basis about git's workflow: http://www.eqqon.com/index.php/Collaborative_Github_Workflow

+ git branching: https://learngitbranching.js.org/

Actually i thought i had more websites saved, but i guess i deleted them some time ago. Feel free to ask if you need help with git's workflow, no problem.

**Pull request merged**
